name: Deploy Static Website with Snyk and EC2

on:
  workflow_dispatch:

jobs:
  security-scan:
    name: Scan for Vulnerabilities with Snyk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Security Scan
        run: snyk test --all-projects
        continue-on-error: true  # Allows the workflow to continue even if vulnerabilities are found

      - name: Monitor with Snyk (optional)
        run: snyk monitor
        continue-on-error: true

  deploy-to-server:
    name: Deploy Static Website to EC2
    needs: security-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Copy Website Files to EC2
        uses: appleboy/scp-action@master
        with:
          host: app.theglorialarbi.com
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./app/*"
          target: "/var/www/html/"

      - name: Restart Nginx on EC2
        uses: appleboy/ssh-action@master
        with:
          host: app.theglorialarbi.com
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: sudo systemctl restart nginx
