name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose whether to apply or destroy Terraform"
        required: true
        type: choice
        options:
          - apply
          - destroy

jobs:
  create-ssm-parameters:
    name: Create SSM Parameters
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra  # Ensure Terraform runs in the right directory
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Apply Only SSM Parameters
        run: |
          terraform apply -target=aws_ssm_parameter.vpc_id \
                         -target=aws_ssm_parameter.public_subnet_id_1 \
                         -target=aws_ssm_parameter.public_subnet_id_2 \
                         -target=aws_ssm_parameter.private_subnet_id \
                         -target=aws_ssm_parameter.igw_id \
                         -auto-approve

  deploy-infrastructure:
    name: Deploy Full Infrastructure
    needs: create-ssm-parameters  # 🚀 Ensures this job runs AFTER SSM parameters are created
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply (Full Infrastructure)
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve

      - name: Terraform Destroy (Optional)
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve
