name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      terraform_action: 
        type: choice
        description: "Choose whether to apply or destroy Terraform"
        options:
          - apply
          - destroy
        required: true

jobs:
  deploy-infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # ✅ Required for OIDC authentication
      contents: read   # ✅ Required to access repository contents

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        if: github.event.inputs.terraform_action == 'apply'
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: github.event.inputs.terraform_action == 'destroy'
        run: terraform destroy -auto-approve
