name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose whether to apply or destroy Terraform"
        required: true
        type: choice
        options:
          - apply
          - destroy

jobs:
  deploy-infrastructure:
    name: Deploy Full Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply (VPC & SSM Parameters First)
        if: github.event.inputs.action == 'apply'
        run: |
          terraform apply \
            -target=aws_vpc.gloria_vpc \
            -target=aws_ssm_parameter.vpc_id \
            -target=aws_ssm_parameter.public_subnet_1_id \
            -target=aws_ssm_parameter.public_subnet_2_id \
            -target=aws_ssm_parameter.private_subnet_id \
            -target=aws_ssm_parameter.igw_id \
            -auto-approve

      - name: Terraform Refresh (Ensure Data Sources Exist)
        if: github.event.inputs.action == 'apply'
        run: terraform refresh

      - name: Terraform Apply (Remaining Infrastructure)
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve

      - name: Ensure SSM Parameters Exist Before Destroy
        if: github.event.inputs.action == 'destroy'
        run: |
          aws ssm get-parameter --name "/terraform/vpc_id" || echo "SSM parameter not found"
          aws ssm get-parameter --name "/terraform/public_subnet_1_id" || echo "SSM parameter not found"
          aws ssm get-parameter --name "/terraform/public_subnet_2_id" || echo "SSM parameter not found"
          aws ssm get-parameter --name "/terraform/private_subnet_id" || echo "SSM parameter not found"
          aws ssm get-parameter --name "/terraform/igw_id" || echo "SSM parameter not found"

      - name: Remove SSM Parameters (Before Destroy)
        if: github.event.inputs.action == 'destroy'
        run: |
          aws ssm delete-parameter --name "/terraform/vpc_id" || echo "Parameter already deleted"
          aws ssm delete-parameter --name "/terraform/public_subnet_1_id" || echo "Parameter already deleted"
          aws ssm delete-parameter --name "/terraform/public_subnet_2_id" || echo "Parameter already deleted"
          aws ssm delete-parameter --name "/terraform/private_subnet_id" || echo "Parameter already deleted"
          aws ssm delete-parameter --name "/terraform/igw_id" || echo "Parameter already deleted"

      - name: Terraform Destroy (Ensure Full Cleanup)
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve
